"""Post-process Orca .gcode.3mf exports for Creality K2 catalog metadata."""
from __future__ import annotations

import hashlib
import json
import re
import zipfile
from pathlib import Path
from tempfile import NamedTemporaryFile

_DEFAULT_DENSITY = 1.24
_HEADER_START = re.compile(r";\s*HEADER_BLOCK_START", re.I)
_MAX_Z = re.compile(r";\s*max_z_height:\s*([\d.]+)", re.I)
_LAYER_HEIGHT = re.compile(r";\s*layer_height\s*=\s*([\d.]+)", re.I)
_LAYER_HEIGHT_ORCA = re.compile(r";\s*Layer height:\s*([\d.]+)", re.I)
_TIME_SECONDS = re.compile(r";\s*TIME:\s*([\d.]+)", re.I)
_TIME_ORCA = re.compile(r";\s*estimated printing time \(normal mode\)\s*=\s*(.+)", re.I)
_FILAMENT_M_ORCA = re.compile(r";\s*Filament used:\s*([\d.]+)m", re.I)
_FILAMENT_MM = re.compile(r";\s*filament used \[mm\]\s*=\s*([\d.]+)", re.I)
_FILAMENT_CM3 = re.compile(r";\s*filament used \[cm3\]\s*=\s*([\d.]+)", re.I)
_PREDICTION = re.compile(r'<metadata key="prediction" value="([^"]+)"')
_USED_M = re.compile(r'used_m="([\d.]+)"')
_USED_G = re.compile(r'used_g="([\d.]+)"')
_WEIGHT = re.compile(r'<metadata key="weight" value="([^"]*)"')
_CREALITY_BLOCK = re.compile(
    r";FLAVOR:Creality OS\s*\r?\n.*?;CREALITY_METADATA_BLOCK_END\s*\r?\n?",
    re.S | re.I,
)
_CONFIG_BLOCK = re.compile(
    r";?\s*CONFIG_BLOCK_START.*?;?\s*CONFIG_BLOCK_END\s*\r?\n?",
    re.S | re.I,
)
_HEADER_BLOCK = re.compile(
    r";?\s*HEADER_BLOCK_START.*?;?\s*HEADER_BLOCK_END\s*\r?\n?",
    re.S | re.I,
)
_FLUSH_MATRIX = re.compile(
    r"(flush_volumes_matrix\s*=\s*)([\d\s.,]+)",
    re.I,
)
_ORCA_GENERATED = re.compile(r";\s*generated by OrcaSlicer[^\n]*", re.I)


def _parse_duration_seconds(raw: str) -> float | None:
    raw = raw.strip()
    if not raw:
        return None
    try:
        return float(raw)
    except ValueError:
        pass
    total = 0.0
    for amount, unit in re.findall(r"(\d+)\s*([hms])", raw, re.I):
        value = int(amount)
        if unit.lower() == "h":
            total += value * 3600
        elif unit.lower() == "m":
            total += value * 60
        else:
            total += value
    return total if total > 0 else None


def _filament_m_from_mm(mm: float) -> float:
    return mm / 1000.0


def _filament_g_from_meters(length_m: float, density: float = _DEFAULT_DENSITY) -> float:
    radius_mm = 1.75 / 2.0
    area_mm2 = 3.141592653589793 * radius_mm * radius_mm
    volume_cm3 = (length_m * 1000.0 * area_mm2) / 1000.0
    return volume_cm3 * density


def _extract_bbox(plate_json: dict) -> tuple[float, float, float, float] | None:
    bbox = plate_json.get("bbox_all")
    if isinstance(bbox, list) and len(bbox) >= 4:
        return float(bbox[0]), float(bbox[1]), float(bbox[2]), float(bbox[3])
    objects = plate_json.get("bbox_objects") or []
    if objects and isinstance(objects[0], dict):
        inner = objects[0].get("bbox")
        if isinstance(inner, list) and len(inner) >= 4:
            return float(inner[0]), float(inner[1]), float(inner[2]), float(inner[3])
    return None


def _object_bounds_from_bbox(
    bbox: tuple[float, float, float, float],
) -> tuple[float, float, float, float] | None:
    """Convert bed-position bbox to 0-origin object dimensions (Creality indexer format)."""
    bx0, by0, bx1, by1 = bbox
    width = bx1 - bx0
    depth = by1 - by0
    if width <= 0 or depth <= 0:
        return None
    return 0.0, 0.0, width, depth


def _header_uses_bed_coords(gcode: str) -> bool:
    hit = re.search(r";\s*MINX:([\d.]+)", gcode)
    if not hit:
        return False
    try:
        return float(hit.group(1)) > 50.0
    except ValueError:
        return False


def _round_flush_volumes_matrix(gcode: str) -> str:
    def _replace(match: re.Match[str]) -> str:
        prefix, raw = match.group(1), match.group(2)
        values = [round(float(part)) for part in raw.split(",") if part.strip()]
        return prefix + ",".join(str(value) for value in values)

    return _FLUSH_MATRIX.sub(_replace, gcode)


def _spoof_creality_slicer_line(gcode: str) -> str:
    return _ORCA_GENERATED.sub("; generated by Creality Print 6.0.0", gcode, count=1)


def _creality_header_at_top(gcode: str) -> bool:
    for line in gcode.splitlines()[:24]:
        stripped = line.strip()
        if stripped.startswith(";FLAVOR:Creality OS"):
            return True
        if stripped.startswith("; HEADER_BLOCK_START"):
            return False
    return False


def _strip_config_block(gcode: str) -> str:
    """Orca CONFIG_BLOCK crashes K2 metadata.py — Creality-native gcode omits it."""
    return _CONFIG_BLOCK.sub("", gcode)


def _strip_orca_header_block(gcode: str) -> str:
    return _HEADER_BLOCK.sub("", gcode)


def _sanitize_k2_flat_gcode(gcode: str) -> str:
    return _strip_config_block(gcode)


def _strip_creality_block(gcode: str) -> str:
    return _CREALITY_BLOCK.sub("", gcode, count=1)


def _build_creality_header(
    *,
    minx: float,
    miny: float,
    maxx: float,
    maxy: float,
    minz: float,
    maxz: float,
    time_sec: float,
    filament_m: float,
    layer_height: float,
    density: float = _DEFAULT_DENSITY,
    filament_cm3: float | None = None,
) -> str:
    weight_g = _filament_g_from_meters(filament_m, density)
    if filament_cm3 is not None and filament_cm3 > 0:
        weight_g = filament_cm3 * density
    lines = [
        ";FLAVOR:Creality OS",
        f";TIME:{time_sec:.2f}",
        f";Filament used:{filament_m:.5f}m",
        f";Material Diameter:1.75",
        f";Material Density:{density:.2f}",
        f";Filament Weight:{weight_g:.6f}",
        f";Filament Length:{filament_m:.6f}",
        f";Layer height:{layer_height:.3f}",
        f";MINX:{minx:.3f}",
        f";MINY:{miny:.3f}",
        f";MINZ:{minz:.3f}",
        f";MAXX:{maxx:.3f}",
        f";MAXY:{maxy:.3f}",
        f";MAXZ:{maxz:.3f}",
        ";CREALITY_METADATA_BLOCK_END",
    ]
    return "\n".join(lines) + "\n"


def _patch_gcode_text(gcode: str, plate_json: dict, slice_info: str) -> str:
    gcode = _strip_creality_block(gcode)

    bbox = _extract_bbox(plate_json)
    if bbox is None:
        return gcode

    minx, miny, maxx, maxy = bbox
    maxz_hit = _MAX_Z.search(gcode)
    maxz = float(maxz_hit.group(1)) if maxz_hit else 0.0
    if maxz <= 0:
        return gcode

    layer_height = 0.2
    for pattern in (_LAYER_HEIGHT, _LAYER_HEIGHT_ORCA):
        hit = pattern.search(gcode)
        if hit:
            layer_height = float(hit.group(1))
            break
    else:
        objects = plate_json.get("bbox_objects") or []
        if objects and isinstance(objects[0], dict) and objects[0].get("layer_height"):
            layer_height = float(objects[0]["layer_height"])

    time_sec: float | None = None
    prediction = _PREDICTION.search(slice_info)
    if prediction:
        try:
            time_sec = float(prediction.group(1))
        except ValueError:
            time_sec = None
    if time_sec is None:
        time_hit = _TIME_ORCA.search(gcode) or _TIME_SECONDS.search(gcode)
        if time_hit:
            time_sec = _parse_duration_seconds(time_hit.group(1))
    if time_sec is None or time_sec <= 0:
        return gcode

    filament_m: float | None = None
    used_m = _USED_M.search(slice_info)
    if used_m:
        filament_m = float(used_m.group(1))
    if filament_m is None:
        hit = _FILAMENT_M_ORCA.search(gcode)
        if hit:
            filament_m = float(hit.group(1))
    if filament_m is None:
        hit = _FILAMENT_MM.search(gcode)
        if hit:
            filament_m = _filament_m_from_mm(float(hit.group(1)))
    if filament_m is None or filament_m <= 0:
        return gcode

    density = _DEFAULT_DENSITY
    density_hit = re.search(r";\s*filament_density:\s*([\d.]+)", gcode, re.I)
    if density_hit:
        parsed = float(density_hit.group(1))
        if parsed > 0:
            density = parsed

    filament_cm3: float | None = None
    cm3_hit = _FILAMENT_CM3.search(gcode)
    if cm3_hit:
        filament_cm3 = float(cm3_hit.group(1))

    block = _build_creality_header(
        minx=minx,
        miny=miny,
        maxx=maxx,
        maxy=maxy,
        minz=layer_height,
        maxz=maxz,
        time_sec=time_sec,
        filament_m=filament_m,
        layer_height=layer_height,
        density=density,
        filament_cm3=filament_cm3,
    )

    gcode = _spoof_creality_slicer_line(gcode)
    gcode = _round_flush_volumes_matrix(gcode)
    if density <= 0 or re.search(r";\s*filament_density:\s*0\s*", gcode, re.I):
        gcode = re.sub(
            r";\s*filament_density:\s*0\s*",
            f"; filament_density: {density}\n",
            gcode,
            count=1,
            flags=re.I,
        )

    return block + gcode.lstrip("\ufeff")


def _patch_slice_info(slice_info: str, *, weight_g: float, used_g: float) -> str:
    weight_text = f"{weight_g:.2f}"
    used_g_text = f"{used_g:.2f}"
    updated = _WEIGHT.sub(f'<metadata key="weight" value="{weight_text}"', slice_info, count=1)
    updated = _USED_G.sub(f'used_g="{used_g_text}"', updated, count=1)
    if 'used_g="' not in updated and 'used_m="' in updated:
        updated = updated.replace(
            'used_m="',
            f'used_g="{used_g_text}" used_m="',
            1,
        )
    return updated


def export_k2_flat_gcode(package_path: Path) -> Path | None:
    """Extract embedded plate gcode as plain .gcode (patch the 3mf package first)."""
    if not package_path.name.lower().endswith(".gcode.3mf"):
        return None
    flat_path = package_path.with_suffix("")  # model.gcode.3mf -> model.gcode
    with zipfile.ZipFile(package_path, "r") as archive:
        gcode_name = next(
            (name for name in ("Metadata/plate_1.gcode", "Metadata/plate_0.gcode") if name in archive.namelist()),
            None,
        )
        if gcode_name is None:
            gcode_name = next(
                (
                    name
                    for name in sorted(archive.namelist())
                    if name.startswith("Metadata/plate_") and name.endswith(".gcode")
                ),
                None,
            )
        if gcode_name is None:
            return None
        gcode = archive.read(gcode_name).decode("utf-8", errors="replace")
    gcode = _sanitize_k2_flat_gcode(gcode)
    flat_path.write_text(gcode, encoding="utf-8")
    return flat_path


def patch_gcode_3mf_for_k2(path: Path, *, density: float = _DEFAULT_DENSITY) -> bool:
    """Inject Creality OS header metadata into an Orca-exported .gcode.3mf."""
    if not path.name.lower().endswith(".gcode.3mf") or not path.is_file():
        return False

    with zipfile.ZipFile(path, "r") as archive:
        names = set(archive.namelist())
        gcode_name = next(
            (name for name in ("Metadata/plate_1.gcode", "Metadata/plate_0.gcode") if name in names),
            None,
        )
        if gcode_name is None:
            gcode_name = next(
                (
                    name
                    for name in sorted(names)
                    if name.startswith("Metadata/plate_") and name.endswith(".gcode")
                ),
                None,
            )
        if gcode_name is None:
            return False

        gcode = archive.read(gcode_name).decode("utf-8", errors="replace")
        plate_json_name = gcode_name.replace(".gcode", ".json")
        slice_info_name = "Metadata/slice_info.config"
        plate_json: dict = {}
        slice_info = ""
        if plate_json_name in names:
            plate_json = json.loads(archive.read(plate_json_name).decode("utf-8"))
        if slice_info_name in names:
            slice_info = archive.read(slice_info_name).decode("utf-8", errors="replace")

        patched_gcode = _patch_gcode_text(gcode, plate_json, slice_info)
        if patched_gcode == gcode:
            return False

        used_m_hit = _USED_M.search(slice_info)
        filament_m = float(used_m_hit.group(1)) if used_m_hit else None
        if filament_m is None:
            hit = _FILAMENT_MM.search(patched_gcode)
            if hit:
                filament_m = _filament_m_from_mm(float(hit.group(1)))
        cm3_hit = _FILAMENT_CM3.search(patched_gcode)
        if cm3_hit:
            weight_g = float(cm3_hit.group(1)) * density
        else:
            weight_g = _filament_g_from_meters(filament_m or 0.0, density) if filament_m else 0.0
        patched_slice_info = (
            _patch_slice_info(slice_info, weight_g=weight_g, used_g=weight_g)
            if slice_info and weight_g > 0
            else slice_info
        )
        gcode_bytes = patched_gcode.encode("utf-8")
        gcode_md5 = hashlib.md5(gcode_bytes).hexdigest()

        with NamedTemporaryFile(delete=False, suffix=".gcode.3mf") as tmp:
            tmp_path = Path(tmp.name)

        with zipfile.ZipFile(tmp_path, "w", compression=zipfile.ZIP_DEFLATED) as out:
            for info in archive.infolist():
                name = info.filename
                if name == gcode_name:
                    out.writestr(name, gcode_bytes)
                elif name == f"{gcode_name}.md5":
                    out.writestr(name, gcode_md5.encode("ascii"))
                elif name == slice_info_name and patched_slice_info:
                    out.writestr(name, patched_slice_info.encode("utf-8"))
                else:
                    out.writestr(info, archive.read(name))

    tmp_path.replace(path)
    return True
