"""Tests for Creality K2 .gcode.3mf metadata patching."""
from __future__ import annotations

import json
import shutil
import tempfile
import unittest
import zipfile
from pathlib import Path

from gcode_3mf_k2 import (
    _build_creality_header,
    _creality_header_at_top,
    _patch_gcode_text,
    _strip_creality_block,
    patch_gcode_3mf_for_k2,
    export_k2_flat_gcode,
)
from creality_preflight import _catalog_entry_for_name, _catalog_lookup_names


class Gcode3mfK2PatchTest(unittest.TestCase):
    def test_build_creality_header_contains_bounds_and_time(self) -> None:
        header = _build_creality_header(
            minx=105.0,
            miny=105.0,
            maxx=155.0,
            maxy=155.0,
            minz=0.2,
            maxz=50.0,
            time_sec=1773.0,
            filament_m=5.51,
            layer_height=0.2,
        )
        self.assertIn(";FLAVOR:Creality OS", header)
        self.assertIn(";TIME:1773.00", header)
        self.assertIn(";MINX:105.000", header)
        self.assertIn(";MAXX:155.000", header)
        self.assertIn(";MAXZ:50.000", header)
        self.assertIn(";Filament used:5.51000m", header)

    def test_patch_gcode_text_prepends_before_header_block(self) -> None:
        gcode = (
            "; HEADER_BLOCK_START\n"
            "; generated by OrcaSlicer 2.3.2\n"
            "; max_z_height: 10.00\n"
            "; HEADER_BLOCK_END\n\n"
            "; estimated printing time (normal mode) = 3m 58s\n"
            "; filament used [mm] = 230.00\n"
        )
        plate_json = {
            "bbox_all": [125.0, 125.0, 135.0, 135.0],
            "bbox_objects": [{"bbox": [125.0, 125.0, 135.0, 135.0], "layer_height": 0.2}],
        }
        slice_info = '<metadata key="prediction" value="238"/>'
        patched = _patch_gcode_text(gcode, plate_json, slice_info)
        self.assertIn(";FLAVOR:Creality OS", patched)
        self.assertLess(patched.index(";FLAVOR:Creality OS"), patched.index("; HEADER_BLOCK_START"))
        self.assertIn(";MINX:125.000", patched)
        self.assertIn(";MAXX:135.000", patched)
        self.assertIn("Creality Print", patched)

    def test_patch_moves_misplaced_creality_block_to_top(self) -> None:
        gcode = (
            "; HEADER_BLOCK_START\n"
            "; max_z_height: 10.00\n"
            "; HEADER_BLOCK_END\n"
            ";FLAVOR:Creality OS\n"
            ";TIME:100.00\n"
            ";Filament used:0.10000m\n"
            ";Material Diameter:1.75\n"
            ";Material Density:1.24\n"
            ";Filament Weight:0.100000\n"
            ";Filament Length:0.100000\n"
            ";Layer height:0.200\n"
            ";MINX:1.000\n"
            ";MINY:1.000\n"
            ";MINZ:0.200\n"
            ";MAXX:2.000\n"
            ";MAXY:2.000\n"
            ";MAXZ:10.000\n"
            ";CREALITY_METADATA_BLOCK_END\n"
            "; estimated printing time (normal mode) = 3m 58s\n"
            "; filament used [mm] = 230.00\n"
        )
        plate_json = {
            "bbox_all": [125.0, 125.0, 135.0, 135.0],
            "bbox_objects": [{"bbox": [125.0, 125.0, 135.0, 135.0], "layer_height": 0.2}],
        }
        slice_info = '<metadata key="prediction" value="238"/> used_m="0.23" used_g="0.00"'
        patched = _patch_gcode_text(gcode, plate_json, slice_info)
        self.assertLess(patched.index(";FLAVOR:Creality OS"), patched.index("; HEADER_BLOCK_START"))
        self.assertEqual(patched.count(";FLAVOR:Creality OS"), 1)

    def test_patch_replaces_bed_coords_header(self) -> None:
        gcode = (
            ";FLAVOR:Creality OS\n"
            ";MINX:120.000\n"
            ";MAXX:140.000\n"
            ";MAXY:140.000\n"
            ";MINY:120.000\n"
            ";MAXZ:20.000\n"
            ";TIME:530.00\n"
            ";Filament used:1.20000m\n"
            ";Material Diameter:1.75\n"
            ";Material Density:1.24\n"
            ";Filament Weight:3.571200\n"
            ";Filament Length:1.200000\n"
            ";Layer height:0.200\n"
            ";MINZ:0.200\n"
            ";CREALITY_METADATA_BLOCK_END\n"
            "; HEADER_BLOCK_START\n"
            "; max_z_height: 20.00\n"
            "; HEADER_BLOCK_END\n"
            "; filament used [mm] = 1200.00\n"
        )
        plate_json = {"bbox_all": [120.0, 120.0, 140.0, 140.0]}
        slice_info = '<metadata key="prediction" value="530"/> used_m="1.20" used_g="3.57"'
        patched = _patch_gcode_text(gcode, plate_json, slice_info)
        self.assertIn(";MINX:120.000", patched)
        self.assertIn(";MAXX:140.000", patched)
        self.assertNotIn(";MINX:0.000", patched.split("; HEADER_BLOCK_START")[0])

    def test_object_bounds_from_bbox(self) -> None:
        from gcode_3mf_k2 import _object_bounds_from_bbox

        self.assertEqual(_object_bounds_from_bbox((120.0, 120.0, 140.0, 140.0)), (0.0, 0.0, 20.0, 20.0))

    def test_strip_creality_block(self) -> None:
        gcode = "prefix\n;FLAVOR:Creality OS\n;TIME:1.00\n;CREALITY_METADATA_BLOCK_END\nsuffix"
        stripped = _strip_creality_block(gcode)
        self.assertNotIn(";FLAVOR:Creality OS", stripped)
        self.assertIn("suffix", stripped)

    def test_strip_config_block(self) -> None:
        from gcode_3mf_k2 import _strip_config_block

        gcode = "head\n; CONFIG_BLOCK_START\n; foo = 1\n; CONFIG_BLOCK_END\ntail"
        stripped = _strip_config_block(gcode)
        self.assertNotIn("CONFIG_BLOCK", stripped)
        self.assertIn("head", stripped)
        self.assertIn("tail", stripped)

    def test_export_flat_gcode(self) -> None:
        source = Path(r"c:\Users\mauri\boat_print\10973edf93a4\model.gcode.3mf")
        if not source.exists():
            self.skipTest("sample 3mf not available")
        with tempfile.TemporaryDirectory() as tmp:
            package = Path(tmp) / source.name
            shutil.copy2(source, package)
            patch_gcode_3mf_for_k2(package)
            flat = export_k2_flat_gcode(package)
            self.assertIsNotNone(flat)
            assert flat is not None
            self.assertTrue(flat.name.endswith(".gcode"))
            self.assertFalse(flat.name.endswith(".gcode.3mf"))
            text = flat.read_text(encoding="utf-8")
            self.assertTrue(text.startswith(";FLAVOR:Creality OS"))
            self.assertNotIn("CONFIG_BLOCK_START", text)

    def test_patch_existing_3mf_package(self) -> None:
        source = Path(r"c:\Users\mauri\boat_print\10973edf93a4\model.gcode.3mf")
        if not source.exists():
            source = Path(r"c:\Users\mauri\boat_print\test_slice_out\test_cube.gcode.3mf")
        if not source.exists():
            self.skipTest("sample 3mf not available")
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp) / source.name
            shutil.copy2(source, target)
            first = patch_gcode_3mf_for_k2(target)
            with zipfile.ZipFile(target) as archive:
                gcode = archive.read("Metadata/plate_1.gcode").decode("utf-8")
                slice_info = archive.read("Metadata/slice_info.config").decode("utf-8")
            self.assertIn(";FLAVOR:Creality OS", gcode)
            self.assertLess(gcode.index(";FLAVOR:Creality OS"), gcode.index("; HEADER_BLOCK_START"))
            self.assertIn(";MINX:120.000", gcode)
            self.assertIn(";MAXX:", gcode)
            self.assertIn('key="weight" value="', slice_info)
            self.assertFalse(patch_gcode_3mf_for_k2(target))
            if not first:
                self.assertTrue(_creality_header_at_top(gcode), "expected header already at top when patch is no-op")


class CatalogLookupTest(unittest.TestCase):
    def test_gcode_3mf_alias(self) -> None:
        names = _catalog_lookup_names("model.gcode.3mf")
        self.assertIn("model.gcode_plate_1.gcode", names)

    def test_catalog_entry_matches_renamed_plate(self) -> None:
        entries = [{"name": "model.gcode_plate_1.gcode", "modelX": 2000, "timeCost": 530}]
        hit = _catalog_entry_for_name(entries, "model.gcode.3mf")
        self.assertIsNotNone(hit)
        self.assertEqual(hit["modelX"], 2000)


if __name__ == "__main__":
    unittest.main()
